<a href="https://colab.research.google.com/github/stefanporosanu/Python-Pandas-Projects/blob/main/Pandas-Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_excel("student.xlsx")
# go to pandas library and use read_excel function
# df is a variable name for data frame

EDA ( Explanatory data analysys)

In [ ]:
# first 5 rows
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
#first 10 rows
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78     NaN
9  10     Big John   Four    55  female

In [ ]:
#return last 5
df.tail()

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
#random sample data
df.sample()

    id    name  class  mark  gender
21  22  Reggid  Seven    55  female

In [ ]:
# number of rows and columns
df.shape
# 35 rows and 5 columns
# no () this is an attribute.

(35, 5)

In [ ]:
# dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

number of entries
data types
non-null count
object64 is a string

In [ ]:
#name of columns
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
#statistical summary
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
# number of rows
len(df)

35

In [ ]:
# rows * columns
df.size

175

In [ ]:
# datatypes of the columns

df.dtypes

id         int64
name      object
class     object
mark       int64
gender    object
dtype: object

In [ ]:
# Counts missing values per column.

df.isnull().sum()

id        0
name      1
class     1
mark      0
gender    2
dtype: int64

In [ ]:
# Counts duplicate rows.

df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
df["class"]

0      Four
1     Three
2     Three
3      Four
4      Four
5      Four
6     Fifth
7      Five
8       Six
9      Four
10      Six
11      Six
12    Seven
13    Seven
14      NaN
15     Four
16      Six
17     Five
18     Nine
19     Nine
20     Four
21    Seven
22    Eight
23    Seven
24    Seven
25    Seven
26    Three
27    Seven
28    Seven
29      Six
30     Four
31    Seven
32      Six
33    Seven
34      Six
Name: class, dtype: object

In [ ]:
df["gender"].head()

0    female
1      male
2      male
3    female
4    female
Name: gender, dtype: object

In [ ]:
df["mark"].max()

96

In [ ]:
df[["gender","mark"]]

    gender  mark
0   female    75
1     male    85
2     male    55
3   female    60
4   female    60
5     male    55
6     male    78
7     male    85
8      NaN    78
9   female    55
10  female    89
11  female    94
12  female    88
13  female    88
14    male    88
15    male    88
16    male    54
17    male    75
18    male    18
19  female    65
20  female    69
21  female    55
22    male    79
23    male    78
24    male    88
25    male    79
26     NaN    81
27  female    86
28    male    55
29  female    79
30    male    88
31  female    90
32  female    96
33    male    69
34  female    88

In [ ]:
df[["name","class","gender"]]

           name  class  gender
0      John Deo   Four  female
1      Max Ruin  Three    male
2        Arnold  Three    male
3    Krish Star   Four  female
4     John Mike   Four  female
5     Alex John   Four    male
6   My John Rob  Fifth    male
7        Asruid   Five    male
8       Tes Qry    Six     NaN
9      Big John   Four  female
10       Ronald    Six  female
11        Recky    Six  female
12          Kty  Seven  female
13         Bigy  Seven  female
14     Tade Row    NaN    male
15        Gimmy   Four    male
16        Tumyu    Six    male
17        Honny   Five    male
18        Tinny   Nine    male
19       Jackly   Nine  female
20   Babby John   Four  female
21       Reggid  Seven  female
22        Herod  Eight    male
23    Tiddy Now  Seven    male
24     Giff Tow  Seven    male
25       Crelea  Seven    male
26          NaN  Three     NaN
27    Rojj Base  Seven  female
28  Tess Played  Seven    male
29    Reppy Red    Six  female
30  Marry Toeey   Four    male
31    Binn Rott  Seven  female
32    Kenn Rein    Six  female
33     Gain Toe  Seven    male
34   Rows Noump    Six  female

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
## name of the student at index 3
df.loc[3, "name"]

'Krish Star'

In [ ]:
#mark of student at index 25
df.loc[25, "mark"]

np.int64(79)

In [ ]:
# name of the student at index 3
df.iloc[3, 1]
# name column is at index 1. Indexes in Python starts from zero. Id is index 0

'Krish Star'

In [ ]:
#mark of student at index 25
df.iloc[25, 3]

np.int64(79)

In [ ]:
#name and gender of the student at index 3
df.loc[3, ["name","gender"]]

name      Krish Star
gender        female
Name: 3, dtype: object

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.loc[[5,15,25],["name","class"]]

         name  class
5   Alex John   Four
15      Gimmy   Four
25     Crelea  Seven

In [ ]:
df.iloc[[5,15,25],[1,2]]

         name  class
5   Alex John   Four
15      Gimmy   Four
25     Crelea  Seven

In [ ]:
df.loc[1:4, ["name","mark"]]

         name  mark
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60
4   John Mike    60

In [ ]:
df.iloc[1:4,[1,3]]

         name  mark
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60

In [ ]:
df[df["mark"]==90]

    id       name  class  mark  gender
31  32  Binn Rott  Seven    90  female

In [ ]:
df[df["gender"] == "female"]

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female
21  22      Reggid  Seven    55  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
31  32   Binn Rott  Seven    90  female
32  33   Kenn Rein    Six    96  female
34  35  Rows Noump    Six    88  female

df[(condition1)&(condition2)]

In [ ]:
# return male students at class four
df[(df["gender"]=="male") & (df["class"]=="Four")]

    id         name class  mark gender
5    6    Alex John  Four    55   male
15  16        Gimmy  Four    88   male
30  31  Marry Toeey  Four    88   male

In [ ]:
df[(df["mark"]<90) & (df["gender"]=="female")]

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female
21  22      Reggid  Seven    55  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
34  35  Rows Noump    Six    88  female

In [ ]:
# average mark of the female student
df[df["gender"]=="female"]["mark"].mean()

np.float64(77.3125)

In [ ]:
# mark > 90 or male student
df[(df["mark"]>90) | (df["gender"]=="male")]

    id         name  class  mark  gender
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
11  12        Recky    Six    94  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
28  29  Tess Played  Seven    55    male
30  31  Marry Toeey   Four    88    male
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male

In [ ]:
df.loc[df["mark"]>80, :]

    id         name  class  mark  gender
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
24  25     Giff Tow  Seven    88    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

In [ ]:
df.loc[(df["mark"]>80) & (df["class"]=="Five"), ["name", "mark"]]
# : means all columns

     name  mark
7  Asruid    85

In [ ]:
df.filter(items=['name', 'mark'])

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
5     Alex John    55
6   My John Rob    78
7        Asruid    85
8       Tes Qry    78
9      Big John    55
10       Ronald    89
11        Recky    94
12          Kty    88
13         Bigy    88
14     Tade Row    88
15        Gimmy    88
16        Tumyu    54
17        Honny    75
18        Tinny    18
19       Jackly    65
20   Babby John    69
21       Reggid    55
22        Herod    79
23    Tiddy Now    78
24     Giff Tow    88
25       Crelea    79
26          NaN    81
27    Rojj Base    86
28  Tess Played    55
29    Reppy Red    79
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

In [ ]:
df.query("mark > 60")

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.query('gender == "female"')

    id        name  class  mark  gender
0    1    John Deo   Four    75  female
3    4  Krish Star   Four    60  female
4    5   John Mike   Four    60  female
9   10    Big John   Four    55  female
10  11      Ronald    Six    89  female
11  12       Recky    Six    94  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
19  20      Jackly   Nine    65  female
20  21  Babby John   Four    69  female
21  22      Reggid  Seven    55  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
31  32   Binn Rott  Seven    90  female
32  33   Kenn Rein    Six    96  female
34  35  Rows Noump    Six    88  female

Average mark across all students

Average mark across male and average mark across female students

Max and min mark

Max mark for male and max mark for female students

Average mark for class 'Five'

Average mark for class 'Six' and male students only

In [ ]:
#1
df["mark"].mean()

np.float64(74.65714285714286)

In [ ]:
#2
df[(df["gender"] == "female")] & df[["mark"].mean()]

df[(df["gender"] == "male") & df[["mark"].mean())]

AttributeError: 'list' object has no attribute 'mean'

In [ ]:
#3
df["mark"].min()

18

In [ ]:
df["mark"].max()

96

In [ ]:
#4
df[df["gender"]=="male"]["mark"].max()

88

In [ ]:
df[df["gender"]=="female"]["mark"].max()

96

In [ ]:
#5
df[df["class"] =="Five"]["mark"].mean()

np.float64(80.0)

In [ ]:
#6
df[(df["class"] =="Six") & (df["gender"] =="male")]["mark"].mean()

np.float64(54.0)

In [ ]:
df.sort_values(by="mark")

    id         name  class  mark  gender
18  19        Tinny   Nine    18    male
16  17        Tumyu    Six    54    male
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
28  29  Tess Played  Seven    55    male
21  22       Reggid  Seven    55  female
9   10     Big John   Four    55  female
4    5    John Mike   Four    60  female
3    4   Krish Star   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
17  18        Honny   Five    75    male
8    9      Tes Qry    Six    78     NaN
23  24    Tiddy Now  Seven    78    male
6    7  My John Rob  Fifth    78    male
22  23        Herod  Eight    79    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
1    2     Max Ruin  Three    85    male
7    8       Asruid   Five    85    male
27  28    Rojj Base  Seven    86  female
12  13          Kty  Seven    88  female
24  25     Giff Tow  Seven    88    male
15  16        Gimmy   Four    88    male
14  15     Tade Row    NaN    88    male
30  31  Marry Toeey   Four    88    male
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
df.sort_values(by="mark", ascending=False)

    id         name  class  mark  gender
32  33    Kenn Rein    Six    96  female
11  12        Recky    Six    94  female
31  32    Binn Rott  Seven    90  female
10  11       Ronald    Six    89  female
30  31  Marry Toeey   Four    88    male
34  35   Rows Noump    Six    88  female
24  25     Giff Tow  Seven    88    male
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
27  28    Rojj Base  Seven    86  female
7    8       Asruid   Five    85    male
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
22  23        Herod  Eight    79    male
6    7  My John Rob  Fifth    78    male
23  24    Tiddy Now  Seven    78    male
8    9      Tes Qry    Six    78     NaN
17  18        Honny   Five    75    male
0    1     John Deo   Four    75  female
33  34     Gain Toe  Seven    69    male
20  21   Babby John   Four    69  female
19  20       Jackly   Nine    65  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
2    3       Arnold  Three    55    male
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
16  17        Tumyu    Six    54    male
18  19        Tinny   Nine    18    male

In [ ]:
df.sort_values(by="class")

    id         name  class  mark  gender
22  23        Herod  Eight    79    male
6    7  My John Rob  Fifth    78    male
17  18        Honny   Five    75    male
7    8       Asruid   Five    85    male
30  31  Marry Toeey   Four    88    male
20  21   Babby John   Four    69  female
15  16        Gimmy   Four    88    male
9   10     Big John   Four    55  female
0    1     John Deo   Four    75  female
5    6    Alex John   Four    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
18  19        Tinny   Nine    18    male
12  13          Kty  Seven    88  female
33  34     Gain Toe  Seven    69    male
25  26       Crelea  Seven    79    male
31  32    Binn Rott  Seven    90  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
13  14         Bigy  Seven    88  female
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female
8    9      Tes Qry    Six    78     NaN
16  17        Tumyu    Six    54    male
11  12        Recky    Six    94  female
10  11       Ronald    Six    89  female
1    2     Max Ruin  Three    85    male
26  27          NaN  Three    81     NaN
2    3       Arnold  Three    55    male
14  15     Tade Row    NaN    88    male

In [ ]:
# return student who are female or at class seven
df[(df["gender"]=="female") | (df["class"]=="Seven")].sort_values(by="mark")

    id         name  class  mark  gender
9   10     Big John   Four    55  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
33  34     Gain Toe  Seven    69    male
0    1     John Deo   Four    75  female
23  24    Tiddy Now  Seven    78    male
29  30    Reppy Red    Six    79  female
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
24  25     Giff Tow  Seven    88    male
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
31  32    Binn Rott  Seven    90  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female

In [ ]:
## How many male and female students are there?
df["gender"].value_counts()

gender
male      17
female    16
Name: count, dtype: int64

In [ ]:
## Class and number of student
df["class"].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Nine      2
Five      2
Fifth     1
Eight     1
Name: count, dtype: int64

In [ ]:
df.sort_values(by=['class', 'mark'], ascending=[False, True])

    id         name  class  mark  gender
2    3       Arnold  Three    55    male
26  27          NaN  Three    81     NaN
1    2     Max Ruin  Three    85    male
16  17        Tumyu    Six    54    male
8    9      Tes Qry    Six    78     NaN
29  30    Reppy Red    Six    79  female
34  35   Rows Noump    Six    88  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
32  33    Kenn Rein    Six    96  female
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
33  34     Gain Toe  Seven    69    male
23  24    Tiddy Now  Seven    78    male
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
24  25     Giff Tow  Seven    88    male
31  32    Binn Rott  Seven    90  female
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
5    6    Alex John   Four    55    male
9   10     Big John   Four    55  female
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
20  21   Babby John   Four    69  female
0    1     John Deo   Four    75  female
15  16        Gimmy   Four    88    male
30  31  Marry Toeey   Four    88    male
17  18        Honny   Five    75    male
7    8       Asruid   Five    85    male
6    7  My John Rob  Fifth    78    male
22  23        Herod  Eight    79    male
14  15     Tade Row    NaN    88    male

In [ ]:
df['class'].value_counts()

class
Seven    10
Four      8
Six       7
Three     3
Nine      2
Five      2
Fifth     1
Eight     1
Name: count, dtype: int64

In [ ]:
df['mark'].value_counts()

mark
88    7
55    5
78    3
79    3
75    2
60    2
85    2
69    2
89    1
54    1
94    1
65    1
18    1
81    1
86    1
90    1
96    1
Name: count, dtype: int64

In [ ]:
df.loc[3:7]

   id         name  class  mark  gender
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male

In [ ]:
df.isnull()

       id   name  class   mark  gender
0   False  False  False  False   False
1   False  False  False  False   False
2   False  False  False  False   False
3   False  False  False  False   False
4   False  False  False  False   False
5   False  False  False  False   False
6   False  False  False  False   False
7   False  False  False  False   False
8   False  False  False  False    True
9   False  False  False  False   False
10  False  False  False  False   False
11  False  False  False  False   False
12  False  False  False  False   False
13  False  False  False  False   False
14  False  False   True  False   False
15  False  False  False  False   False
16  False  False  False  False   False
17  False  False  False  False   False
18  False  False  False  False   False
19  False  False  False  False   False
20  False  False  False  False   False
21  False  False  False  False   False
22  False  False  False  False   False
23  False  False  False  False   False
24  False  False  False  False   False
25  False  False  False  False   False
26  False   True  False  False    True
27  False  False  False  False   False
28  False  False  False  False   False
29  False  False  False  False   False
30  False  False  False  False   False
31  False  False  False  False   False
32  False  False  False  False   False
33  False  False  False  False   False
34  False  False  False  False   False